### ISSUE TITLE
Variable Declaration and String Value Assignment Detection Issue (Intro) 

### ISSUE THREAD

**Issue by IceBytes** [TeaByte/NakhlahJS#35]
The current code fails to accurately detect cases where a variable is declared and assigned a string value, especially when the declaration and assignment occur on separate lines. This results in false positives or inaccurate results when evaluating code submissions.

The regex pattern used in the code is insufficient to handle cases where a variable is declared and then assigned a string value elsewhere in the code. This limitation affects the reliability of the code checker.

A revised regex pattern needs to be implemented to ensure accurate detection of variable declaration and string value assignment, regardless of their placement within the code.

Kindly review and address this issue to enhance the effectiveness of the code evaluation process.

Thank you!

**Comment by TeaByte** [comment]
fixed
